name: CI

on: [ push, pull_request ]

jobs:
  test:

    runs-on: ubuntu-latest

    # not setting up a matrix strategy because the project uses sbt-projectmatrix

    steps:
      - uses: actions/checkout@v5

      - uses: coursier/cache-action@v6

      - name: setup Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'sbt'

      - name: setup SBT
        uses: sbt/setup-sbt@v1

      - name: build
        run: sbt clean check coverage test

      - name: test coverage
        if: success()
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
        run: sbt coverageReport coverageAggregate coveralls

      - name: slack
        uses: homoluctus/slatify@master
        if: failure() && github.ref == 'refs/heads/master'
        with:
          type: ${{ job.status }}
          job_name: Build
          url: ${{ secrets.SLACK_WEBHOOK }}